#!/bin/bash
# Keep-Alive Service Setup Script
# Helps you set up automatic pinging to keep your site awake

echo ""
echo "=========================================================="
echo "   🔄 Keep Your Website Always Awake - Setup Guide"
echo "=========================================================="
echo ""

echo "Choose your setup option:"
echo ""
echo "1️⃣  Upgrade to Paid Tier on Render.com ($7/month) - RECOMMENDED"
echo "   - Always-on, instant loads"
echo "   - Go to: https://dashboard.render.com"
echo ""
echo "2️⃣  Use UptimeRobot for Free Monitoring"
echo "   - Go to: https://uptimerobot.com"
echo "   - Add HTTP monitor: https://your-site.onrender.com/_health"
echo "   - Interval: 5 minutes"
echo ""
echo "3️⃣  Run DIY Keep-Alive Service Locally"
echo "   - Requires: Node.js running 24/7 on your machine"
echo ""
echo "4️⃣  Combine 1 + 2 (Best Setup)"
echo "   - Render Paid ($7) + UptimeRobot monitoring (Free)"
echo ""
echo "=========================================================="
echo ""
echo "ℹ️  All options are already configured!"
echo ""
echo "Your health check endpoint:"
echo "   https://your-site.onrender.com/_health"
echo ""
echo "To test locally:"
echo "   curl http://localhost:5000/_health"
echo ""
echo "=========================================================="
echo ""
echo "📖 For detailed instructions, see: KEEP_ALIVE_GUIDE.md"
echo ""
