(async function(){
  const fetch = globalThis.fetch;
  const base = 'https://www.tilana.online/api';
  const email = 'admin@tilana.online';
  const password = 'YourStrongPassword123!';
  try{
    console.log('Logging in...');
    const r1 = await fetch(base + '/auth/login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ email, password }) });
    const j1 = await r1.json().catch(()=>null);
    console.log('Login status', r1.status);
    console.log('Login response', JSON.stringify(j1));
    if(!r1.ok || !j1 || !j1.token){
      console.error('Login failed, aborting');
      process.exit(1);
    }
    const token = j1.token || j1.data?.token || j1.accessToken;
    console.log('Token obtained:', !!token);

    const postBody = {
      title: 'Automated test post '+ new Date().toISOString(),
      category: 'Testing',
      excerpt: 'This is a test post created by an automated script.',
      content: '<p>Test post content (draft) generated by bot.</p>',
      published: false
    };

    console.log('Creating post (draft)...');
    const r2 = await fetch(base + '/posts', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-auth-token': token }, body: JSON.stringify(postBody) });
    const j2 = await r2.json().catch(()=>null);
    console.log('Create status', r2.status);
    console.log('Create response', JSON.stringify(j2));
    if(r2.ok && j2 && j2.success){
      console.log('Post created OK. ID/slug:', j2.post && (j2.post.id || j2.post.slug));
      process.exit(0);
    } else {
      console.error('Post creation failed');
      process.exit(2);
    }
  }catch(e){
    console.error('Exception', e);
    process.exit(3);
  }
})();